export const GET_VEHICLES = 'GET_VEHICLE';
export const GET_PARKINGS = 'GET_PARKING';
export const GET_POI = 'GET_POI';

export const CHANGE_TAB = 'CHANGE_TAB';
export const TAB_TOGGLE = 'TAB_TOGGLE';

export const FILTERS_CHANGE_NAME = 'FILTERS_CHANGE_NAME';
export const FILTERS_CHANGE_OBJECT_TYPE = 'FILTERS_CHANGE_OBJECT_TYPE';
export const FILTERS_CHANGE_BATTERY_LEVEL = 'FILTERS_CHANGE_BATTERY_LEVEL';
export const FILTERS_CHANGE_VEHICLE_STATUS = 'FILTERS_CHANGE_VEHICLE_STATUS';
export const FILTERS_CHANGE_VEHICLE_TYPE = 'FILTERS_CHANGE_VEHICLE_TYPE';
export const FILTERS_CHANGE_VEHICLE_COLORS = 'FILTERS_CHANGE_VEHICLE_COLORS';
export const FILTERS_CHANGE_VEHICLE_PLATES = 'FILTERS_CHANGE_VEHICLE_PLATES';
export const FILTERS_CHANGE_VEHICLE_NUMBERS = 'FILTERS_CHANGE_VEHICLE_NUMBERS';
export const FILTERS_CHANGE_PARKING_AVAILABLE_SPACE = 'FILTERS_CHANGE_PARKING_AVAILABLE_SPACE';